M48
; DRILL file {KiCad 7.0.6} date Wed Aug  2 22:02:10 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-02T22:02:10+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X8.0474Y-4.1862
X8.0474Y-4.4138
T2
X3.663Y-3.48
X3.9386Y-3.48
T0
M30
